
---
- name: Deploying Changes via CVP
  hosts: cv_server
  connection: local
  gather_facts: false

  tasks:
    - name: Run CVP provisioning
      ansible.builtin.import_role:
          name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: "DC_FABRIC"
        configlets_prefix: "AVD"
        state: present
        execute_tasks: true
        device_filter: ''
